#!/bin/bash

# Specifica il percorso del file
file="/data/data/com.termux/files/home/.termux/termux.properties"

# Crea la directory se non esiste
mkdir -p "$(dirname "$file")"

# Aggiungi le linee al file
echo "allow-external-apps=true" >> "$file"
echo "hide-soft-keyboard-on-startup=true" >> "$file"

# Ricarica le impostazioni di Termux
termux-reload-settings

# Installa i pacchetti richiesti accettando automaticamente
yes | pkg install android-tools
yes | pkg install root-repo

# Install wget
yes | pkg install wget

# Scarico installAndLaunch dal mio portfolio
wget https://raw.githubusercontent.com/danieledellacioppa/danieledellacioppa.github.io/refs/heads/main/installAndLaunch

# Mostra la lista dei pacchetti aggiornabili
apt list --upgradable

# Aggiorna i pacchetti installati accettando automaticamente
yes | pkg upgrade


