name: Build, Upload Artifact, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Install Dependencies
        run: npm install

      # - name: CI
      #   run: npm run ci
    
      - name: Build
        run: npm run build
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/
  
  deploy:
    needs: build-and-upload
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment # Assicurati che l'indentazione sia corretta qui
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist


        



